from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.http import JsonResponse
import json
import requests

# Create your views here.

categories_attributes = json.loads("""{
    \"C__CATG__GLOBAL\": [\"id\", \"title\", \"status\", \"created\", \"created_by\", \"changed\", \"changed_by\", \"purpose\", \"category\", \"sysid\", \"cmdb_status\", \"type\", \"tag\", \"description\"], \"C__CATG__MODEL\": [\"manufacturer\", \"title\", \"productid\", \"service_tag\", \"serial\", \"firmware\", \"description\"], \"C__CATG__FORMFACTOR\": [\"formfactor\", \"rackunits\", \"unit\", \"width\", \"height\", \"depth\", \"weight\", \"weight_unit\", \"description\"], \"C__CATG__CPU\": [\"title\", \"manufacturer\", \"type\", \"frequency\", \"frequency_unit\", \"cores\", \"description\"], \"C__CATG__MEMORY\": [\"quantity\", \"title\", \"manufacturer\", \"type\", \"total_capacity\", \"capacity\", \"unit\", \"description\"], \"C__CATG__NETWORK\": [\"title\", \"manufacturer\", \"model\", \"serial\", \"slot\", \"description\"], \"C__CATG__POWER_CONSUMER\": [\"title\", \"active\", \"manufacturer\", \"model\", \"volt\", \"watt\", \"ampere\", \"btu\", \"assigned_connector\", \"connector\", \"connector_sibling\", \"description\"], \"C__CATG__UNIVERSAL_INTERFACE\": [\"title\", \"type\", \"plug\", \"assigned_connector\", \"connector\", \"connector_sibling\", \"description\", \"relation_direction\"], \"C__CATG__APPLICATION\": [\"application\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_database_schema\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"bequest_nagios_services\", \"assigned_databases\", \"description\"], \"C__CATG__ACCESS\": [\"primary_url\", \"title\", \"type\", \"url\", \"formatted_url\", \"primary\", \"description\"], \"C__CATG__BACKUP\": [\"title\", \"backup\", \"backup_type\", \"cycle\", \"path_to_save\", \"description\"], \"C__CATG__EMERGENCY_PLAN\": [\"title\", \"emergency_plan\", \"time_needed\", \"time_needed_unit\", \"practice_date\", \"description\"], \"C__CATG__FILE\": [\"file\", \"revision\", \"link\", \"description\"], \"C__CATG__CONTACT\": [\"contact\", \"primary_contact\", \"contact_object\", \"primary\", \"role\", \"contact_list\", \"contact_list_with_roles\", \"description\"], \"C__CATG__LOGBOOK\": [\"date\", \"object\", \"event\", \"source\", \"user\", \"object_type\", \"category\", \"alert_level\", \"user_name_static\", \"event_static\", \"comment\", \"changes\", \"reason\", \"description\"], \"C__CATG__CONTROLLER\": [\"title\", \"type\", \"manufacturer\", \"model\", \"firmware\", \"description\"], \"C__CATG__LOCATION\": [\"location_path\", \"parent\", \"option\", \"insertion\", \"pos\", \"gps\", \"latitude\", \"longitude\", \"snmp_syslocation\", \"description\"], \"C__CATG__IMAGE\": [\"image_selection\", \"image\", \"description\"], \"C__CATG__MANUAL\": [\"title\", \"manual\", \"description\"], \"C__CATG__OVERVIEW\": [], \"C__CATG__SOUND\": [\"manufacturer\", \"title\", \"description\"], \"C__CATG__OBJECT\": [\"assigned_object\"], \"C__CATG__GRAPHIC\": [\"title\", \"manufacturer\", \"memory\", \"unit\", \"firmware\", \"description\"], \"C__CATG__VIRTUAL_MACHINE\": [\"virtual_machine\", \"hosts\", \"system\", \"config_file\", \"primary\", \"description\"], \"C__CATG__ACCOUNTING\": [\"inventory_no\", \"account\", \"acquirementdate\", \"contact\", \"price\", \"operation_expense\", \"operation_expense_interval\", \"cost_unit\", \"delivery_note_no\", \"procurement\", \"delivery_date\", \"invoice_no\", \"order_no\", \"guarantee_period\", \"guarantee_period_unit\", \"guarantee_period_status\", \"guarantee_period_base\", \"order_date\", \"guarantee_date\", \"guarantee_status\", \"description\"], \"C__CATG__NETWORK_PORT\": [\"title\", \"interface\", \"port_type\", \"port_mode\", \"plug_type\", \"negotiation\", \"duplex\", \"speed\", \"speed_type\", \"standard\", \"mac\", \"mtu\", \"assigned_connector\", \"connector\", \"connector_sibling\", \"cable\", \"active\", \"addresses\", \"layer2_assignment\", \"hba\", \"default_vlan\", \"description\", \"relation_direction\"], \"C__CATG__NETWORK_INTERFACE\": [\"title\", \"manufacturer\", \"model\", \"serial\", \"slot\", \"description\"], \"C__CATG__NETWORK_LOG_PORT\": [\"title\", \"net\", \"mac\", \"port_type\", \"ports\", \"parent\", \"standard\", \"active\", \"addresses\", \"assigned_connector\", \"description\"], \"C__CATG__DRIVE\": [\"mount_point\", \"title\", \"system_drive\", \"filesystem\", \"capacity\", \"unit\", \"serial\", \"assigned_raid\", \"drive_type\", \"device\", \"raid\", \"ldev\", \"category_const\", \"free_space\", \"free_space_unit\", \"used_space\", \"used_space_unit\", \"firmware\", \"description\"], \"C__CATG__STORAGE_DEVICE\": [\"type\", \"title\", \"manufacturer\", \"model\", \"unit\", \"capacity\", \"hotspare\", \"connected\", \"controller\", \"raid_group\", \"serial\", \"description\", \"lto_type\", \"fc_address\", \"firmware\"], \"C__CATG__CONTROLLER_FC_PORT\": [\"title\", \"type\", \"connected_controller\", \"connector_sibling\", \"medium\", \"speed\", \"speed_unit\", \"wwn\", \"wwpn\", \"san_zones\", \"target\", \"connector\", \"assigned_connector\", \"description\", \"relation_direction\"], \"C__CATG__IP\": [\"primary_layer3_net\", \"primary_hostaddress\", \"primary_hostname\", \"net_type\", \"primary\", \"active\", \"net\", \"zone\", \"ipv4_assignment\", \"ipv4_address\", \"ipv6_assignment\", \"ipv6_scope\", \"ipv6_address\", \"hostaddress\", \"hostname\", \"domain\", \"dns_server\", \"dns_server_address\", \"dns_domain\", \"use_standard_gateway\", \"assigned_port\", \"assigned_logical_port\", \"all_ips\", \"primary_fqdn\", \"aliases\", \"description\"], \"C__CATG__VERSION\": [\"title\", \"servicepack\", \"kernel\", \"patchlevel\", \"description\"], \"C__CATG__CONNECTOR\": [\"title\", \"type\", \"wiring_system\", \"interface\", \"fiber_wave_lengths\", \"connection_type\", \"assigned_connector\", \"assigned_category\", \"cable_connection\", \"used_fiber_lead_rx\", \"used_fiber_lead_tx\", \"connector_sibling\", \"description\", \"relation_direction\"], \"C__CATG__INVOICE\": [\"denotation\", \"date\", \"amount\", \"edited\", \"financial_accounting_delivery\", \"charged\", \"description\"], \"C__CATG__POWER_SUPPLIER\": [\"title\", \"volt\", \"watt\", \"ampere\", \"assigned_connector\", \"connector\", \"connector_sibling\", \"assigned_category\", \"description\"], \"C__CATG__RAID\": [\"raid_type\", \"title\", \"raid_level\", \"controller\", \"storages\", \"full_capacity\", \"capacity\", \"description\"], \"C__CATG__LDEV_SERVER\": [\"title\", \"lun\", \"segment_size\", \"unit\", \"capacity\", \"connected_devices\", \"paths\", \"primary_path\", \"multipath\", \"tierclass\", \"ldev_clients\", \"description\"], \"C__CATG__LDEV_CLIENT\": [\"title\", \"paths\", \"assigned_ldevserver\", \"primary_path\", \"multipath\", \"description\"], \"C__CATG__HBA\": [\"title\", \"type\", \"manufacturer\", \"model\", \"firmware\", \"description\"], \"C__CATG__CLUSTER_ROOT\": [\"quorum\", \"administration_service\", \"cluster_members\", \"cluster_member_count\", \"cluster_service\", \"description\"], \"C__CATG__CLUSTER\": [\"quorum\", \"administration_service\", \"cluster_members\", \"cluster_member_count\", \"cluster_service\", \"description\"], \"C__CATG__SHARES\": [\"title\", \"unc_path\", \"volume\", \"path\", \"description\"], \"C__CATG__CLUSTER_SERVICE\": [\"type\", \"cluster_service\", \"hostaddresses\", \"drives\", \"shares\", \"runs_on\", \"default_server\", \"assigned_database_schema\", \"service_status\", \"description\"], \"C__CATG__CLUSTER_MEMBERS\": [\"member\"], \"C__CATG__CLUSTER_MEMBERSHIPS\": [\"connected_object\"], \"C__CATG__COMPUTING_RESOURCES\": [\"ram\", \"ram_unit\", \"cpu\", \"cpu_unit\", \"disc_space\", \"disc_space_unit\", \"network_bandwidth\", \"network_bandwidth_unit\", \"description\"], \"C__CATG__SNMP\": [\"title\", \"description\"], \"C__CATG__VIRTUAL_HOST_ROOT\": [\"virtual_host\", \"license_server\", \"administration_service\", \"description\"], \"C__CATG__VIRTUAL_HOST\": [\"virtual_host\", \"license_server\", \"administration_service\", \"description\"], \"C__CATG__GUEST_SYSTEMS\": [\"connected_object\", \"hostname\", \"runs_on\"], \"C__CATG__VIRTUAL_MACHINE__ROOT\": [\"virtual_machine\", \"hosts\", \"system\", \"config_file\", \"primary\", \"description\"], \"C__CATG__VIRTUAL_SWITCH\": [\"title\", \"ports\", \"portgroup\", \"serviceconsoleports\", \"vmkernelports\", \"description\"], \"C__CATG__VIRTUAL_DEVICE\": [\"host_stor_device\", \"host_ldev_client\", \"host_drive\", \"host_port\", \"host_interface\", \"host_raid\", \"local_stor_device\", \"local_port\", \"local_interface\", \"storage_type\", \"network_type\", \"switch_port_group\", \"cluster_storage\", \"cluster_interface\", \"disk_image_location\", \"device_type\", \"description\", \"virtual_network_type\"], \"C__CATG__BACKUP__ASSIGNED_OBJECTS\": [\"title\", \"backup\", \"backup_type\", \"cycle\", \"path_to_save\", \"description\"], \"C__CATG__GROUP_MEMBERSHIPS\": [\"connected_object\", \"description\"], \"C__CATG__IT_SERVICE_COMPONENTS\": [\"connected_object\", \"objtype\"], \"C__CATG__ITS_LOGBOOK\": [\"date\", \"object\", \"event\", \"source\", \"user\", \"object_type\", \"category\", \"alert_level\", \"user_name_static\", \"event_static\", \"comment\", \"changes\", \"description\"], \"C__CATG__IT_SERVICE\": [\"connected_object\", \"sysid\"], \"C__CATG__RELATION\": [\"object1\", \"object2\", \"relation_type\", \"weighting\", \"itservice\", \"description\"], \"C__CATG__IT_SERVICE_RELATIONS\": [\"object1\", \"object2\", \"relation_type\", \"weighting\", \"itservice\", \"description\"], \"C__CATG__DATABASE_ASSIGNMENT\": [\"database_assignment\", \"runs_on\", \"description\"], \"C__CATG__ITS_TYPE\": [\"its_type\", \"description\"], \"C__CATG__PASSWD\": [\"title\", \"username\", \"password\", \"description\"], \"C__CATG__SOA_STACKS\": [\"title\", \"soa_stack_object\", \"soa_stack_components\", \"soa_stack_it_services\", \"description\"], \"C__CATG__ASSIGNED_CARDS\": [\"connected_obj\"], \"C__CATG__SIM_CARD\": [\"type\", \"assigned_mobile\", \"network_provider\", \"telephone_rate\", \"start\", \"end\", \"threshold_date\", \"card_no\", \"phone_no\", \"client_no\", \"pin\", \"pin2\", \"puk\", \"puk2\", \"serial\", \"twincard\", \"tc_card_no\", \"tc_phone_no\", \"tc_pin\", \"tc_pin2\", \"tc_puk\", \"tc_puk2\", \"tc_serial_no\", \"optional_info\", \"description\"], \"C__CATG__TSI_SERVICE\": [\"tsi_service_id\", \"description\"], \"C__CATG__AUDIT\": [\"title\", \"type\", \"commission\", \"responsible\", \"involved\", \"period_manufacturer\", \"period_operator\", \"apply\", \"result\", \"fault\", \"incident\", \"description\"], \"C__CATG__LOGICAL_UNIT\": [\"parent\", \"description\"], \"C__CATG__ASSIGNED_LOGICAL_UNIT\": [\"assigned_object\"], \"C__CATG__ASSIGNED_WORKSTATION\": [\"parent\", \"description\"], \"C__CATG__PERSON_ASSIGNED_WORKSTATION\": [\"assigned_workstations\", \"description\"], \"C__CATG__CONTRACT_ASSIGNMENT\": [\"connected_contract\", \"contract_start\", \"contract_end\", \"reaction_rate\", \"description\"], \"C__CATG__MAIL_ADDRESSES\": [\"title\", \"primary_mail\", \"primary\", \"description\"], 
    \"C__CATG__VOIP_PHONE\": [\"device_protocol\", \"description2\", \"device_pool\", \"common_configuration\", \"button_template\", \"softkey_template\", \"common_profile\", \"calling_search_space\", \"aar_calling_search_space\", \"media_resource_group_list\", \"user_hold_moh_audio_source\", \"network_hold_moh_audio_source\", \"location\", \"aar_group\", \"user_locale\", \"network_locale\", \"built_in_bridge\", \"privacy\", \"device_mobility_mode\", \"owner_user_id\", \"phone_suite\", \"services_provisioning\", \"load_name\", \"description\"], \"C__CATG__VOIP_PHONE_LINE\": [\"directory_number\", \"route_partition\", \"description2\", \"alerting_name\", \"ascii_alerting_name\", \"allow_cti_control\", \"associated_devices\", \"voice_mail_profile\", \"calling_search_space\", \"presence_group\", \"user_hold_moh_audio_source\", \"network_hold_moh_audio_source\", \"auto_answer\", \"call_forward_all\", \"sec_calling_search_space\", \"forward_busy_internal\", \"forward_busy_external\", \"forward_no_answer_internal\", \"forward_no_answer_external\", \"forward_no_coverage_internal\", \"forward_no_coverage_external\", \"forward_on_cti_fail\", \"forward_unregistered_internal\", \"forward_unregistered_external\", \"no_answer_ring_duration\", \"call_pickup_group\", \"display\", \"ascii_display\", \"line_text_label\", \"ascii_line_text_label\", \"visual_message_indicator\", \"audible_message_indicator\", \"ring_settings_idle\", \"ring_settings_active\", \"call_pickup_group_idle\", \"call_pickup_group_active\", \"recording_option\", \"recording_profile\", \"monitoring_css\", \"log_missed_calls\", \"external_phone_number_mask\", \"max_number_of_calls\", \"busy_trigger\", \"caller_name\", \"caller_number\", \"redirected_number\", \"dialed_number\", \"description\"], \"C__CATG__TELEPHONE_FAX\": [\"type\", \"telephone_number\", \"fax_number\", \"extension\", \"pincode\", \"imei\", \"description\"], \"C__CATG__SMARTCARD_CERTIFICATE\": [\"cardnumber\", \"barring_password\", \"pin_nr\", \"reference\", \"expires_on\", \"description\"], \"C__CATG__SHARE_ACCESS\": [\"assigned_objects\", \"mountpoint\", \"shares\", \"description\"], \"C__CATG__CERTIFICATE\": [\"type\", \"create_date\", \"expire_date\", \"common_name\", \"description\"], \"C__CATG__SLA\": [\"service_id\", \"service_level\", \"service_level_dialog\", \"days\", \"monday_time\", \"tuesday_time\", \"wednesday_time\", \"thursday_time\", \"friday_time\", \"saturday_time\", \"sunday_time\", \"reaction_time\", \"reaction_time_unit\", \"recovery_time\", \"recovery_time_unit\", \"calendar\", \"description\"], \"C__CATG__LDAP_DN\": [\"title\", \"description\"], \"C__CATG__ADDRESS\": [\"address\", \"street\", \"house_no\", \"stories\", \"postcode\", \"city\", \"region\", \"country\", \"description\"], \"C__CATG__MONITORING\": [\"active\", \"monitoring_host\", \"host_name\", \"host_name_selection\", \"description\"], \"C__CATG__VEHICLE\": [\"licence_plate\", \"description\"], \"C__CATG__AIRCRAFT\": [\"registration\", \"description\"], \"C__CATG__NET_CONNECTIONS_FOLDER\": [\"protocol\", \"protocol_layer_5\", \"ip_address\", \"port_from\", \"port_to\", \"opened_by\", \"gateway\", \"description\"], \"C__CATG__NET_LISTENER\": [\"protocol\", \"protocol_layer_5\", \"ip_address\", \"port_from\", \"port_to\", \"opened_by\", \"gateway\", \"description\"], \"C__CATG__NET_CONNECTOR\": [\"ip_address\", \"port_from\", \"port_to\", \"connected_listener\", \"connected_to\", \"gateway\", \"description\"], \"C__CATG__CLUSTER_ADM_SERVICE\": [\"connected_object\", \"objtype\"], \"C__CATG__JDISC_CA\": [\"attribute\", \"attribute_content\", \"attribute_type\", \"attribute_folder\", \"description\"], \"C__CATG__CABLE\": [\"cable_type\", \"cable_colour\", \"cable_occupancy\", \"length\", \"length_unit\", \"max_amount_of_fibers_leads\", \"connection\", \"description\"], \"C__CATG__IDENTIFIER\": [\"key\", \"value\", \"last_edited\", \"type\", \"group\", \"last_scan\", \"last_updated\", \"description\"], \"C__CATG__SERVICE\": [\"service_number\", \"type\", \"category\", \"business_unit\", \"active\", \"service_description_intern\", \"service_description_extern\", \"service_alias\", \"description\"], \"C__CATG__OPERATING_SYSTEM\": [\"application\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"assigned_databases\", \"description\"], \"C__CATG__QINQ_SP\": [\"spvlan\", \"description\"], \"C__CATG__FIBER_LEAD\": [\"label\", \"category\", \"color\", \"damping\", \"description\"], \"C__CATG__QINQ_CE\": [\"spvlan\"], \"C__CATG__WAN\": [\"title\", \"role\", \"type\", \"channels\", \"call_numbers\", \"connection_location\", \"capacity_up\", \"capacity_up_unit\", \"capacity_down\", \"capacity_down_unit\", \"max_capacity_up\", \"max_capacity_up_unit\", \"max_capacity_down\", \"max_capacity_down_unit\", \"project_no\", \"vlan_id\", \"shopping_cart_no\", \"ticket_no\", \"customer_no\", \"router\", \"net\", \"description\"], \"C__CATG__RM_CONTROLLER\": [\"remote_url\", \"connected_object\", \"description\"], \"C__CATG__RM_CONTROLLER_BACKWARD\": [\"connected_object\"], \"C__CATG__MANAGED_OBJECTS\": [\"connected_object\"], \"C__CATG__VRRP\": [\"type\", \"vrid\", \"description\"], \"C__CATG__VRRP_MEMBER\": [\"member\", \"description\"], \"C__CATG__STACK_MEMBER\": [\"assigned_object\", \"mode\", \"description\"], \"C__CATG__LAST_LOGIN_USER\": [\"last_login\", \"type\", \"description\"], \"C__CATG__NET_ZONE_OPTIONS\": [\"color\", \"domain\", \"description\"], \"C__CATG__DATABASE\": [\"assigned_dbms\", \"instance_name\", \"instance_type\", \"manufacturer\", \"size\", \"size_unit\", \"version\", \"path\", \"port\", \"port_name\", \"import_key\", \"description\"], \"C__CATG__DATABASE_TABLE\": [\"title\", \"row_count\", \"assigned_database\", \"instance\", \"assigned_schema\", \"schema_size\", \"schema_size_unit\", \"size\", \"size_unit\", \"max_size\", \"max_size_unit\", \"import_key\", \"description\"], \"C__CATG__DATABASE_SA\": [\"assigned_database\", \"assigned_instance\", \"assigned_schemas\", \"title\", \"size\", \"size_unit\", \"max_size\", \"max_size_unit\", \"import_key\", \"description\"], \"C__CATG__SIM\": [\"type\", \"network_provider\", \"telephone_rate\", \"start\", \"end\", \"threshold_date\", \"phone_no\", \"client_no\", \"description\"], \"C__CATG__CARDS\": [\"assigned_mobile\", \"card_no\", \"title\", \"pin\", \"pin2\", \"puk\", \"puk2\", \"serial\", \"description\"], \"C__CATG__ASSIGNED_SIM_CARDS\": [\"isys_obj__id\", \"isys_catg_cards_list__id\"], \"C__CATG__CLOUD_SUBSCRIPTIONS\": [\"uuid\", \"consumed_units\", \"prepaid_enabled_units\", \"prepaid_suspended\", \"prepaid_warning\", \"jdisc_status\", \"subscribers\", \"description\"], \"C__CATG__ASSIGNED_SUBSCRIPTIONS\": [\"assigned_object\", \"uuid\", \"description\"], \"C__CATG__ASSIGNED_USERS\": [\"assigned_object\", \"uuid\", \"description\"], \"C__CATS__ROOM\": [\"type\", \"number\", \"floor\", \"description\"], \"C__CATS__SERVICE\": [\"specification\", \"manufacturer\", \"installation\", \"registration_key\", \"install_path\", \"installation_count\", \"description\"], \"C__CATS__SWITCH_NET\": [\"vlan\", \"role\", \"spanning_tree\", \"description\"], \"C__CATS__WAN\": [\"role\", \"type\", \"capacity\", \"capacity_unit\", \"description\"], \"C__CATS__EMERGENCY_PLAN\": [\"time_needed\", \"time_unit\", \"practice_date\", \"description\"], \"C__CATS__AC\": [\"type\", \"threshold\", \"threshold_unit\", \"capacity_unit\", \"capacity\", \"air_quantity\", \"air_quantity_unit\", \"width\", \"height\", \"depth\", \"dimension_unit\", \"description\"], \"C__CATS__ACCESS_POINT\": [\"title\", \"function\", \"standard\", \"channel\", \"broadcast_ssid\", \"ssid\", \"mac_filter\", \"auth\", \"encryption_id\", \"key\", \"description\"], \"C__CATS__MONITOR\": [\"size\", \"size_unit\", \"type\", \"resolution\", \"pivot\", \"speaker\", \"description\"], \"C__CATS__CLIENT\": [\"type\", \"keyboard_layout\", \"description\"], \"C__CATS__SWITCH_FC\": [\"title\", \"is_active\", \"description\"], \"C__CATS__ROUTER\": [\"routing_protocol\", \"gateway_address\", \"description\"], \"C__CATS__PRT\": [\"type\", \"is_color\", \"is_duplex\", \"emulation\", \"paper_format\", \"description\"], \"C__CATS__FILE\": [\"file_title\", \"file_physical\", \"file_category\", \"revision\", \"version_description\", \"description\", \"current_version\", \"md5_hash\"], \"C__CATS__APPLICATION\": [\"specification\", \"manufacturer\", \"installation\", \"registration_key\", \"install_path\", \"installation_count\", \"description\"], \"C__CATS__NET\": [\"title\", \"type\", \"address\", \"netmask\", \"gateway\", \"range_from\", \"range_to\", \"dns_server\", \"dns_domain\", \"cidr_suffix\", \"reverse_dns\", \"layer2_assignments\", \"address_v6\", \"address_range\", \"address_with_suffix\", \"free_addresses\", \"description\"], \"C__CATS__CELL_PHONE_CONTRACT\": [\"imei_number\", \"description\"], \"C__CATS__LICENCE\": [], \"C__CATS__GROUP\": [\"object\", \"object_type\", \"description\"], \"C__CATS__LICENCE_LIST\": [\"key\", \"serial\", \"type\", \"amount\", \"used_licences\", \"lic_not_in_use\", \"start\", \"expire\", \"cost\", \"overall_costs\", \"description\"], \"C__CATS__FILE_ACTUAL\": [\"file_title\", \"file_physical\", \"file_category\", \"revision\", \"version_description\", \"description\", \"current_version\", \"md5_hash\"], \"C__CATS__FILE_VERSIONS\": [\"file_physical\", \"file_content\", \"file_title\", \"revision\", \"upload_date\", \"version_description\", \"md5_hash\", \"uploaded_by\"], \"C__CATS__FILE_OBJECTS\": [\"assigned_objects\"], \"C__CATS__EMERGENCY_PLAN_ATTRIBUTE\": [\"time_needed\", \"time_unit\", \"practice_date\", \"description\"], \"C__CATS__EMERGENCY_PLAN_LINKED_OBJECTS\": [\"object\"], \"C__CATS__WS_NET_TYPE\": [\"title\", \"description\"], \"C__CATS__WS_ASSIGNMENT\": [\"connected_object\"], \"C__CATS__WS\": [\"title\", \"description\"], \"C__CATS__UPS\": [\"type\", \"battery_type\", \"amount\", \"charge_time\", \"charge_time_unit\", \"autonomy_time\", \"autonomy_time_unit\", \"description\"], \"C__CATS__EPS\": [\"type\", \"warmup_time\", \"warmup_time_unit\", \"fuel_tank\", \"volume_unit\", \"autonomy_time\", \"autonomy_time_unit\", \"description\"], \"C__CATS__SAN_ZONING\": [\"title\", \"members\", \"description\"], \"C__CATS__ORGANIZATION\": [\"title\", \"telephone\", \"fax\", \"website\", \"headquarter\", \"description\"], \"C__CATS__ORGANIZATION_MASTER_DATA\": [\"title\", \"telephone\", \"fax\", \"website\", \"headquarter\", \"description\"], \"C__CATS__ORGANIZATION_PERSONS\": [\"object\", \"contact\"], \"C__CATS__PERSON\": [\"title\", \"salutation\", \"first_name\", \"last_name\", \"academic_degree\", \"function\", \"service_designation\", \"street\", \"city\", \"zip_code\", \"mail\", \"phone_company\", \"phone_home\", \"phone_mobile\", \"fax\", \"pager\", \"personnel_number\", \"department\", \"organization\", \"ldap_id\", \"ldap_dn\", \"description\", \"custom_1\", \"custom_2\", \"custom_3\", \"custom_4\", \"custom_5\", \"custom_6\", \"custom_7\", \"custom_8\"], 
    \"C__CATS__PERSON_MASTER\": [\"title\", \"salutation\", \"first_name\", \"last_name\", \"academic_degree\", \"function\", \"service_designation\", \"street\", \"city\", \"zip_code\", \"mail\", \"phone_company\", \"phone_home\", \"phone_mobile\", \"fax\", \"pager\", \"personnel_number\", \"department\", \"organization\", \"ldap_id\", \"ldap_dn\", \"description\", \"custom_1\", \"custom_2\", \"custom_3\", \"custom_4\", \"custom_5\", \"custom_6\", \"custom_7\", \"custom_8\"], \"C__CATS__PERSON_LOGIN\": [\"disabled_login\", \"title\", \"user_pass\", \"user_pass2\", \"description\", \"custom_1\", \"custom_2\", \"custom_3\", \"custom_4\", \"custom_5\", \"custom_6\", \"custom_7\", \"custom_8\"], \"C__CATS__PERSON_ASSIGNED_GROUPS\": [\"connected_object\", \"contact\"], \"C__CATS__PERSON_GROUP\": [\"title\", \"email_address\", \"phone\", \"ldap_group\", \"description\"], \"C__CATS__PERSON_GROUP_MASTER\": [\"title\", \"email_address\", \"phone\", \"ldap_group\", \"description\"], \"C__CATS__PERSON_GROUP_MEMBERS\": [\"first_name\", \"last_name\", \"department\", \"phone_company\", \"email_address\", \"organization\", \"title\", \"connected_object\"], \"C__CATS__ORGANIZATION_CONTACT_ASSIGNMENT\": [\"object\", \"role\"], \"C__CATS__PERSON_CONTACT_ASSIGNMENT\": [\"object\", \"object_type\", \"role\", \"description\"], \"C__CATS__PERSON_GROUP_CONTACT_ASSIGNMENT\": [\"object\", \"object_type\", \"role\", \"description\"], \"C__CATS__CLUSTER_SERVICE\": [\"cluster\", \"type\", \"runs_on\", \"default_server\", \"hostaddresses\", \"drives\", \"shares\", \"assigned_database_schema\", \"service_status\", \"description\"], \"C__CATS__RELATION_DETAILS\": [\"object1\", \"object2\", \"itservice\", \"relation_type\", \"weighting\", \"description\"], \"C__CATS__DATABASE_SCHEMA\": [\"link\", \"instance\", \"title\", \"storage_engine\", \"description\"], \"C__CATS__DATABASE_LINKS\": [\"title\", \"link\", \"target_user\", \"owner\", \"public\", \"description\"], \"C__CATS__DBMS\": [\"dbms\", \"description\"], \"C__CATS__DATABASE_INSTANCE\": [\"instance\", \"title\", \"listener\", \"database_schema\", \"description\"], \"C__CATS__PDU\": [\"pdu_id\", \"description\"], \"C__CATS__PDU_BRANCH\": [\"pdu_id\", \"branch_id\", \"receptables\", \"description\"], \"C__CATS__PARALLEL_RELATION\": [\"title\", \"threshold\", \"rel_pool\", \"description\"], \"C__CATS__DATABASE_OBJECTS\": [\"title\", \"database_object\", \"description\"], \"C__CATS__DATABASE_ACCESS\": [\"access\"], \"C__CATS__DATABASE_GATEWAY\": [\"type\", \"host\", \"port\", \"user\", \"target_schema\", \"description\"], \"C__CATS__REPLICATION\": [\"replication_mechanism\", \"description\"], \"C__CATS__REPLICATION_PARTNER\": [\"type\", \"replication_partner\", \"description\"], \"C__CATS__APPLICATION_ASSIGNED_OBJ\": [\"object\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_database_schema\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"bequest_nagios_services\", \"description\"], \"C__CATS__CLUSTER_SERVICE_ASSIGNED_OBJ\": [], \"C__CATS__MIDDLEWARE\": [\"specification\", \"manufacturer\", \"installation\", \"registration_key\", \"install_path\", \"installation_count\", \"description\"], \"C__CATS__KRYPTO_CARD\": [\"certificate_number\", \"certgate_card_number\", \"certificate_title\", \"certificate_password\", \"certificate_procedure\", \"date_of_issue\", \"imei_number\", \"assigned_mobile\", \"description\"], \"C__CATS__NET_DHCP\": [\"type\", \"typev6\", \"range_from\", \"range_to\", \"description\"], \"C__CATS__LAYER2_NET\": [\"vlan_id\", \"standard\", \"type\", \"subtype\", \"ip_helper_addresses\", \"layer3_assignments\", \"vrf\", \"vrf_capacity\", \"vrf_capacity_unit\", \"description\"], \"C__CATS__LAYER2_NET_ASSIGNED_PORTS\": [\"isys_obj__id\", \"isys_catg_port_list__id\", \"isys_catg_port_list__mac\"], \"C__CATS__CONTRACT\": [\"type\", \"contract_no\", \"customer_no\", \"internal_no\", \"costs\", \"cost_calculation\", \"product\", \"reaction_rate\", \"contract_status\", \"start_date\", \"end_date\", \"run_time\", \"run_time_unit\", \"next_contract_end_date\", \"end_type\", \"next_notice_end_date\", \"notice_date\", \"notice_period\", \"notice_period_unit\", \"notice_type\", \"maintenance_period\", \"maintenance_period_unit\", \"payment_period\", \"description\"], \"C__CATS__CONTRACT_INFORMATION\": [\"type\", \"contract_no\", \"customer_no\", \"internal_no\", \"costs\", \"cost_calculation\", \"product\", \"reaction_rate\", \"contract_status\", \"start_date\", \"end_date\", \"run_time\", \"run_time_unit\", \"next_contract_end_date\", \"end_type\", \"next_notice_end_date\", \"notice_date\", \"notice_period\", \"notice_period_unit\", \"notice_type\", \"maintenance_period\", \"maintenance_period_unit\", \"payment_period\", \"description\"], \"C__CATS__CONTRACT_ALLOCATION\": [\"assigned_object\"], \"C__CATS__CHASSIS_SLOT\": [\"connector_type\", \"insertion\", \"title\", \"from_x\", \"to_x\", \"from_y\", \"to_y\", \"assigned_devices\", \"description\"], \"C__CATS__CHASSIS_DEVICES\": [\"role\", \"assigned_device\", \"assigned_hba\", \"assigned_interface\", \"assigned_power_consumer\", \"assigned_slots\", \"description\"], \"C__CATS__APPLICATION_VARIANT\": [\"title\", \"variant\", \"description\"], \"C__CATS__LAYER2_NET_ASSIGNED_LOGICAL_PORTS\": [\"isys_obj__id\", \"isys_catg_log_port_list__id\"], \"C__CATS__APPLICATION_SERVICE_ASSIGNED_OBJ\": [\"object\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_database_schema\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"bequest_nagios_services\", \"description\"], \"C__CATS__APPLICATION_DBMS_ASSIGNED_OBJ\": [\"object\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_database_schema\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"bequest_nagios_services\", \"description\"], \"C__CATS__NET_ZONE\": [\"zone\", \"range_from\", \"range_from_long\", \"range_to\", \"range_to_long\", \"description\"], \"C__CATS__OPERATING_SYSTEM\": [\"specification\", \"manufacturer\", \"installation\", \"registration_key\", \"install_path\", \"installation_count\", \"description\"], \"C__CATS__DATABASE_INSTALLATION\": [\"object\", \"application_type\", \"application_priority\", \"assigned_license\", \"assigned_license_key\", \"assigned_database_schema\", \"assigned_it_service\", \"assigned_variant\", \"assigned_version\", \"bequest_nagios_services\", \"description\", \"assigned_databases\"]
}""")

response = json.loads("""{
    \"id\":1,
    \"jsonrpc\":\"2.0\",
    \"result\":{
        \"objectTypes\":{
            \"C__OBJTYPE__SERVICE\":\"System Service\",
            \"C__OBJTYPE__APPLICATION\":\"Application\",
            \"C__OBJTYPE__BUILDING\":\"Building\",
            \"C__OBJTYPE__ENCLOSURE\":\"Rack\",
            \"C__OBJTYPE__SERVER\":\"Server\",
            \"C__OBJTYPE__SWITCH\":\"Switch\",
            \"C__OBJTYPE__ROUTER\":\"Router\",
            \"C__OBJTYPE__FC_SWITCH\":\"Fc Switch\",
            \"C__OBJTYPE__SAN\":\"Storage System\",
            \"C__OBJTYPE__CLIENT\":\"Client\",
            \"C__OBJTYPE__PRINTER\":\"Printer\",
            \"C__OBJTYPE__AIR_CONDITION_SYSTEM\":\"Air Condition System\",
            \"C__OBJTYPE__WAN\":\"Wan\",
            \"C__OBJTYPE__EMERGENCY_PLAN\":\"Emergency Plan\",
            \"C__OBJTYPE__KVM_SWITCH\":\"Kvm Switch\",
            \"C__OBJTYPE__MONITOR\":\"Monitor\",
            \"C__OBJTYPE__APPLIANCE\":\"Appliance\",
            \"C__OBJTYPE__TELEPHONE_SYSTEM\":\"Telephone System\",
            \"C__OBJTYPE__PRINTBOX\":\"Printbox\",
            \"C__OBJTYPE__ROOM\":\"Room\",
            \"C__OBJTYPE__ACCESS_POINT\":\"Wireless Access Point\",
            \"C__OBJTYPE__MAINTENANCE\":\"Contract\",
            \"C__OBJTYPE__FILE\":\"File\",
            \"C__OBJTYPE__LOCATION_GENERIC\":\"Generic Location\",
            \"C__OBJTYPE__LAYER3_NET\":\"Layer 3-net\",
            \"C__OBJTYPE__CELL_PHONE_CONTRACT\":\"Cellular Phone\",
            \"C__OBJTYPE__LICENCE\":\"Licenses\",
            \"C__OBJTYPE__CONTAINER\":\"Container\",
            \"C__OBJTYPE__OPERATING_SYSTEM\":\"Operating System\",
            \"C__OBJECT_TYPE__GROUP\":\"Object Group\",
            \"C__OBJTYPE__GENERIC_TEMPLATE\":\"Generic Template\",
            \"C__OBJTYPE__PHONE\":\"Phone\",
            \"C__OBJTYPE__HOST\":\"Host\",
            \"C__OBJTYPE__CABLE\":\"Cable\",
            \"C__OBJTYPE__CONVERTER\":\"Converter\",
            \"C__OBJTYPE__WIRING_SYSTEM\":\"Wiring System\",
            \"C__OBJTYPE__PATCH_PANEL\":\"Patch Panel\",
            \"C__OBJTYPE__AMPLIFIER\":\"Amplifier\",
            \"C__OBJTYPE__IT_SERVICE\":\"Service\",
            \"C__OBJTYPE__ESC\":\"Electric Power Company\",
            \"C__OBJTYPE__EPS\":\"Emergency Power Supply\",
            \"C__OBJTYPE__DISTRIBUTION_BOX\":\"Distribution Box\",
            \"C__OBJTYPE__PDU\":\"Power Distribution Unit\",
            \"C__OBJTYPE__UPS\":\"Uninterruptible Power Supply\",
            \"C__OBJTYPE__SAN_ZONING\":\"San Zoning\",
            \"C__OBJTYPE__ORGANIZATION\":\"Organization\",
            \"C__OBJTYPE__PERSON\":\"Persons\",
            \"C__OBJTYPE__PERSON_GROUP\":\"Person Groups\",
            \"C__OBJTYPE__CLUSTER\":\"Cluster\",
            \"C__OBJTYPE__CLUSTER_SERVICE\":\"Cluster Services\",
            \"C__OBJTYPE__VIRTUAL_CLIENT\":\"Virtual Client\",
            \"C__OBJTYPE__VIRTUAL_HOST\":\"Virtual Host\",
            \"C__OBJTYPE__VIRTUAL_SERVER\":\"Virtual Server\",
            \"C__OBJTYPE__RELATION\":\"Relation\",
            \"C__OBJTYPE__DBMS\":\"Dbms\",
            \"C__OBJTYPE__DATABASE_SCHEMA\":\"Database Schema\",
            \"C__OBJTYPE__PARALLEL_RELATION\":\"Parallel Relations\",
            \"C__OBJTYPE__REPLICATION\":\"Replication Object\",
            \"C__OBJTYPE__DATABASE_INSTANCE\":\"Database Instance\",
            \"C__OBJTYPE__MIDDLEWARE\":\"Middleware\",
            \"C__OBJTYPE__SOA_STACK\":\"Soa Stack\",
            \"C__OBJTYPE__KRYPTO_CARD\":\"Crypto Card\",
            \"C__OBJTYPE__SIM_CARD\":\"Sim Card\",
            \"C__OBJTYPE__LAYER2_NET\":\"Layer 2 Net\",
            \"C__OBJTYPE__WORKSTATION\":\"Workplace\",
            \"C__OBJTYPE__MIGRATION_OBJECT\":\"Migration Objects\",
            \"C__OBJTYPE__SWITCH_CHASSIS\":\"Switch Chassis\",
            \"C__OBJTYPE__BLADE_CHASSIS\":\"Blade Chassis\",
            \"C__OBJTYPE__BLADE_SERVER\":\"Blade Server\",
            \"C__OBJTYPE__VOIP_PHONE\":\"Voip Telephone\",
            \"C__OBJTYPE__SUPERNET\":\"Supernet\",
            \"C__OBJTYPE__VEHICLE\":\"Vehicle\",
            \"C__OBJTYPE__AIRCRAFT\":\"Aircraft\",
            \"C__OBJTYPE__CLUSTER_VRRP_HSRP\":\"Vrrp\/hsrp Cluster\",
            \"C__OBJTYPE__COUNTRY\":\"Country\",
            \"C__OBJTYPE__CITY\":\"City\",
            \"C__CMDB__OBJTYPE__CABLE_TRAY\":\"Cable Tray\",
            \"C__CMDB__OBJTYPE__CONDUIT\":\"Conduit\",
            \"C__OBJTYPE__RM_CONTROLLER\":\"Remote Management Controller\",
            \"C__OBJTYPE__VRRP\":\"Vrrp\",
            \"C__OBJTYPE__STACKING\":\"Stacking\",
            \"C__OBJTYPE__NET_ZONE\":\"Net Zone\",
            \"C__OBJTYPE__RACK_SEGMENT\":\"Rack Segment\"
        },
        \"categories\":{
            \"g\":{
                \"C__CATG__GLOBAL\":\"General\",
                \"C__CATG__MODEL\":\"Model\",
                \"C__CATG__FORMFACTOR\":\"Form factor\",
                \"C__CATG__CPU\":\"CPU\",
                \"C__CATG__MEMORY\":\"Memory\",
                \"C__CATG__NETWORK\":\"Network\",
                \"C__CATG__STORAGE\":\"Direct Attached Storage\",
                \"C__CATG__POWER_CONSUMER\":\"Power consumer\",
                \"C__CATG__UNIVERSAL_INTERFACE\":\"Interface\",
                \"C__CATG__APPLICATION\":\"Software assignment\",
                \"C__CATG__ACCESS\":\"Access\",
                \"C__CATG__BACKUP\":\"Backup\",
                \"C__CATG__EMERGENCY_PLAN\":\"Emergency plan assignment\",
                \"C__CATG__FILE\":\"Files\",
                \"C__CATG__CONTACT\":\"Contact assignment\",
                \"C__CATG__LOGBOOK\":\"Logbook\",
                \"C__CATG__CONTROLLER\":\"Controller\",
                \"C__CATG__LOCATION\":\"Location\",
                \"C__CATG__IMAGE\":\"Object picture\",
                \"C__CATG__MANUAL\":\"Manual assignment\",
                \"C__CATG__OVERVIEW\":\"Overview page\",
                \"C__CATG__SOUND\":\"Sound card\",
                \"C__CATG__OBJECT\":\"locally assigned objects\",
                \"C__CATG__GRAPHIC\":\"Graphic card\",
                \"C__CATG__VIRTUAL_MACHINE\":\"Virtual machine\",
                \"C__CATG__ACCOUNTING\":\"Accounting\",
                \"C__CATG__NETWORK_PORT\":\"Port\",
                \"C__CATG__NETWORK_INTERFACE\":\"Interface\",
                \"C__CATG__NETWORK_LOG_PORT\":\"logical Ports\",
                \"C__CATG__DRIVE\":\"Drive\",
                \"C__CATG__STORAGE_DEVICE\":\"Device\",
                \"C__CATG__CONTROLLER_FC_PORT\":\"FC port\",
                \"C__CATG__SANPOOL\":\"Storage Area Network\",
                \"C__CATG__IP\":\"Host address\",
                \"C__CATG__VERSION\":\"Version\",
                \"C__CATG__CABLING\":\"Cabling\",
                \"C__CATG__CONNECTOR\":\"Connectors\",
                \"C__CATG__INVOICE\":\"Invoice\",
                \"C__CATG__CUSTOM_FIELDS\":\"Custom Fields\",
                \"C__CATG__POWER_SUPPLIER\":\"Power supplier\",
                \"C__CATG__RAID\":\"Raid-Array\",
                \"C__CATG__LDEV_SERVER\":\"Logical devices (LDEV Server)\",
                \"C__CATG__LDEV_CLIENT\":\"Logical devices (Client)\",
                \"C__CATG__HBA\":\"Host Bus Adapter (HBA)\",
                \"C__CATG__CLUSTER_ROOT\":\"Cluster\",
                \"C__CATG__CLUSTER\":\"Cluster\",
                \"C__CATG__SHARES\":\"Shares\",
                \"C__CATG__CLUSTER_SERVICE\":\"Cluster service assignment\",
                \"C__CATG__CLUSTER_MEMBERS\":\"Cluster Members\",
                \"C__CATG__CLUSTER_MEMBERSHIPS\":\"Cluster memberships\",
                \"C__CATG__COMPUTING_RESOURCES\":\"Computing resources\",
                \"C__CATG__SNMP\":\"SNMP\",
                \"C__CATG__VIRTUAL_HOST_ROOT\":\"Virtual host\",
                \"C__CATG__VIRTUAL_HOST\":\"Virtual host\",
                \"C__CATG__GUEST_SYSTEMS\":\"Guest systems\",
                \"C__CATG__VIRTUAL_MACHINE__ROOT\":\"Virtual machine\",
                \"C__CATG__VIRTUAL_SWITCH\":\"Virtual Switches\",
                \"C__CATG__VIRTUAL_DEVICE\":\"Virtual devices\",
                \"C__CATG__BACKUP__ASSIGNED_OBJECTS\":\"Backup (assigned Objects)\",
                \"C__CATG__GROUP_MEMBERSHIPS\":\"Group memberships\",
                \"C__CATG__IT_SERVICE_COMPONENTS\":\"Service components\",
                \"C__CATG__ITS_LOGBOOK\":\"Service Logbook\",
                \"C__CATG__IT_SERVICE\":\"Service assignment\",
                \"C__CATG__RELATION\":\"Relationship\",
                \"C__CATG__IT_SERVICE_RELATIONS\":\"Service Relation\",
                \"C__CATG__DATABASE_ASSIGNMENT\":\"Database assignment\",
                \"C__CATG__ITS_TYPE\":\"Service Type\",
                \"C__CATG__PASSWD\":\"Passwords\",
                \"C__CATG__SOA_STACKS\":\"SOA-Stacks\",
                \"C__CATG__ASSIGNED_CARDS\":\"Assigned cards\",
                \"C__CATG__SIM_CARD\":\"SIM card\",
                \"C__CATG__TSI_SERVICE\":\"TSI service\",
                \"C__CATG__AUDIT\":\"Audit\",
                \"C__CATG__LOGICAL_UNIT\":\"Logical location\",
                \"C__CATG__ASSIGNED_LOGICAL_UNIT\":\"Workplace components\",
                \"C__CATG__ASSIGNED_WORKSTATION\":\"Assigned workstation\",
                \"C__CATG__VIRTUAL_TICKETS\":\"All Tickets\",
                \"C__CATG__PERSON_ASSIGNED_WORKSTATION\":\"Assigned Workplaces\",
                \"C__CATG__CONTRACT_ASSIGNMENT\":\"Contract assignment\",
                \"C__CATG__MAIL_ADDRESSES\":\"E-Mail addresses\",
                \"C__CATG__VOIP_PHONE\":\"CUCM VoIP telephone\",
                \"C__CATG__VOIP_PHONE_LINE\":\"CUCM VoIP line\",
                \"C__CATG__TELEPHONE_FAX\":\"Telephone\/Fax\",
                \"C__CATG__SMARTCARD_CERTIFICATE\":\"Smart Card Certificate\",
                \"C__CATG__SHARE_ACCESS\":\"Share Access\",
                \"C__CATG__CERTIFICATE\":\"Certificate\",
                \"C__CATG__SLA\":\"SLA\",
                \"C__CATG__LDAP_DN\":\"LDAP\",
                \"C__CATG__ADDRESS\":\"Address\",
                \"C__CATG__MONITORING\":\"Monitoring\",
                \"C__CATG__LIVESTATUS\":\"Livestatus\",
                \"C__CATG__VEHICLE\":\"Vehicle\",
                \"C__CATG__AIRCRAFT\":\"Aircraft\",
                \"C__CATG__NET_CONNECTIONS_FOLDER\":\"Network connections\",
                \"C__CATG__NET_LISTENER\":\"Listener\",
                \"C__CATG__NET_CONNECTOR\":\"Connection\",
                \"C__CATG__CLUSTER_ADM_SERVICE\":\"Administration service\",
                \"C__CATG__JDISC_CA":"JDisc Custom Attributes",
                \"C__CATG__NDO\":\"NDO\",
                \"C__CATG__CABLE\":\"Cable\",
                \"C__CATG__IDENTIFIER\":\"Data Source\",
                \"C__CATG__SERVICE\":\"Services\",
                \"C__CATG__OPERATING_SYSTEM\":\"Operating system\",
                \"C__CATG__JDISC_DISCOVERY\":\"JDisc Discovery\",
                \"C__CATG__QINQ_SP\":\"QinQ SP-VLAN\",
                \"C__CATG__FIBER_LEAD\":\"Fiber\/lead\",
                \"C__CATG__QINQ_CE\":\"QinQ CE-VLAN\",
                \"C__CATG__IMAGES\":\"LC__CATG__IMAGES\",
                \"C__CATG__WAN\":\"WAN Connection\",
                \"C__CATG__RM_CONTROLLER\":\"Remote Management Controller\",
                \"C__CATG__RM_CONTROLLER_BACKWARD\":\"Managed devices\",
                \"C__CATG__MANAGED_OBJECTS\":\"Virtual managed objects\",
                \"C__CATG__VRRP\":\"VRRP\",
                \"C__CATG__VRRP_MEMBER\":\"VRRP Member\",
                \"C__CATG__VRRP_VIEW\":\"VRRP membership\",
                \"C__CATG__STACK_MEMBER\":\"Stack member\",
                \"C__CATG__STACK_MEMBERSHIP\":\"Stack membership\",
                \"C__CATG__LAST_LOGIN_USER\":\"Last login user\",
                \"C__CATG__NET_ZONE\":\"Net zone\",
                \"C__CATG__NET_ZONE_OPTIONS\":\"Options\",
                \"C__CATG__NET_ZONE_SCOPES\":\"Scope\",
                \"C__CATG__CABLE_CONNECTION\":\"Cable connection\",
                \"C__CATG__MULTIEDIT\":\"Listedit\",
                \"C__CATG__DATABASE_FOLDER\":\"Databases\",
                \"C__CATG__DATABASE\":\"DBMS\",
                \"C__CATG__DATABASE_TABLE\":\"Tables\",
                \"C__CATG__DATABASE_SA\":\"Databases\",
                \"C__CATG__SIM\":\"SIM\",
                \"C__CATG__CARDS\":\"Cards\",
                \"C__CATG__ASSIGNED_SIM_CARDS\":\"Assigned SIM cards\",
                \"C__CATG__CLOUD_SUBSCRIPTIONS\":\"Subscriptions\",
                \"C__CATG__ASSIGNED_SUBSCRIPTIONS\":\"Assigned Subscriptions\",
                \"C__CATG__ASSIGNED_USERS\":\"Assigned Users\"
            },
            \"s\":{
                \"C__CATS__ROOM\":\"Room\",
                \"C__CATS__SERVICE\":\"Services\",
                \"C__CATS__SWITCH_NET\":\"Switch\",
                \"C__CATS__WAN\":\"WAN\",
                \"C__CATS__EMERGENCY_PLAN\":\"Emergency plan\",
                \"C__CATS__AC\":\"Air conditioning\",
                \"C__CATS__ACCESS_POINT\":\"WiFi device\",
                \"C__CATS__MONITOR\":\"Monitor\",
                \"C__CATS__CLIENT\":\"Desktop\",
                \"C__CATS__SWITCH_FC\":\"FC switch\",
                \"C__CATS__ROUTER\":\"Routing\",
                \"C__CATS__PRT\":\"Printer\",
                \"C__CATS__FILE\":\"Files\",
                \"C__CATS__APPLICATION\":\"Applications\",
                \"C__CATS__NET\":\"Net\",
                \"C__CATS__CELL_PHONE_CONTRACT\":\"Mobile radio\",
                \"C__CATS__LICENCE\":\"Licenses\",
                \"C__CATS__GROUP\":\"Object group\",
                \"C__CATS__LICENCE_LIST\":\"License keys\",
                \"C__CATS__FILE_ACTUAL\":\"Current file\",
                \"C__CATS__FILE_VERSIONS\":\"File versions\",
                \"C__CATS__FILE_OBJECTS\":\"Assigned objects\",
                \"C__CATS__EMERGENCY_PLAN_ATTRIBUTE\":\"Emergency plan properties\",
                \"C__CATS__EMERGENCY_PLAN_LINKED_OBJECTS\":\"assigned objects\",
                \"C__CATS__WS_NET_TYPE\":\"Net type\",
                \"C__CATS__WS_ASSIGNMENT\":\"Assigned objects\",
                \"C__CATS__WS\":\"Wiring System\",
                \"C__CATS__UPS\":\"Uninterruptible power supply\",
                \"C__CATS__EPS\":\"Emergency power supply\",
                \"C__CATS__SAN_ZONING\":\"SAN Zoning\",
                \"C__CATS__ORGANIZATION\":\"Organization\",
                \"C__CATS__ORGANIZATION_MASTER_DATA\":\"Master data\",
                \"C__CATS__ORGANIZATION_PERSONS\":\"Persons\",
                \"C__CATS__PERSON\":\"Persons\",
                \"C__CATS__PERSON_MASTER\":\"Master Data\",
                \"C__CATS__PERSON_LOGIN\":\"Login\",
                \"C__CATS__PERSON_ASSIGNED_GROUPS\":\"Person group memberships\",
                \"C__CATS__PERSON_GROUP\":\"Person groups\",
                \"C__CATS__PERSON_GROUP_MASTER\":\"Master Data\",
                \"C__CATS__PERSON_GROUP_MEMBERS\":\"Members\",
                \"C__CATS__ORGANIZATION_CONTACT_ASSIGNMENT\":\"Assigned Objects\",
                \"C__CATS__PERSON_CONTACT_ASSIGNMENT\":\"Assigned Objects\",
                \"C__CATS__PERSON_GROUP_CONTACT_ASSIGNMENT\":\"Assigned Objects\",
                \"C__CATS__CLUSTER_SERVICE\":\"Assigned clusters\",
                \"C__CATS__RELATION_DETAILS\":\"Relation details\",
                \"C__CATS__DATABASE_SCHEMA\":\"Database schema\",
                \"C__CATS__DATABASE_LINKS\":\"Database links\",
                \"C__CATS__DBMS\":\"DBMS\",
                \"C__CATS__DATABASE_INSTANCE\":\"Instance \/ Oracle database\",
                \"C__CATS__PDU\":\"PDU\",
                \"C__CATS__PDU_BRANCH\":\"Branch\",
                \"C__CATS__PARALLEL_RELATION\":\"Parallel relations\",
                \"C__CATS__DATABASE_OBJECTS\":\"Database objects\",
                \"C__CATS__DATABASE_ACCESS\":\"Database access\",
                \"C__CATS__DATABASE_GATEWAY\":\"Database gateway\",
                \"C__CATS__REPLICATION\":\"Replication\",
                \"C__CATS__REPLICATION_PARTNER\":\"Replication partner\",
                \"C__CATS__APPLICATION_ASSIGNED_OBJ\":\"Installation\",
                \"C__CATS__CLUSTER_SERVICE_ASSIGNED_OBJ\":\"Cluster installation\",
                \"C__CATS__MIDDLEWARE\":\"Middleware\",
                \"C__CATS__KRYPTO_CARD\":\"Crypto card\",
                \"C__CATS__NET_DHCP\":\"DHCP\",
                \"C__CATS__LAYER2_NET\":\"Layer 2 Net\",
                \"C__CATS__LAYER2_NET_ASSIGNED_PORTS\":\"Assigned ports\",
                \"C__CATS__CONTRACT\":\"Contract\",
                \"C__CATS__CONTRACT_INFORMATION\":\"Contract information\",
                \"C__CATS__CONTRACT_ALLOCATION\":\"Assigned Objects\",
                \"C__CATS__CHASSIS\":\"Chassis\",
                \"C__CATS__CHASSIS_SLOT\":\"Slots\",
                \"C__CATS__CHASSIS_DEVICES\":\"Assigned devices\",
                \"C__CATS__CHASSIS_CABLING\":\"Cabling\",
                \"C__CATS__APPLICATION_VARIANT\":\"Variants\",
                \"C__CATS__BASIC_AUTH\":\"Authorization config\",
                \"C__CATS__GROUP_TYPE\":\"Type\",
                \"C__CATS__LAYER2_NET_ASSIGNED_LOGICAL_PORTS\":\"Assigned logical ports\",
                \"C__CATS__APPLICATION_SERVICE_ASSIGNED_OBJ\":\"Installation\",
                \"C__CATS__APPLICATION_DBMS_ASSIGNED_OBJ\":\"Installation\",
                \"C__CATS__NET_ZONE\":\"Net zone\",
                \"C__CATS__OPERATING_SYSTEM\":\"Operating Systems\",
                \"C__CATS__DATABASE_INSTALLATION\":\"Database installation\"
            }
        },
        \"recordStates\":{
            \"C__RECORD_STATUS__NORMAL\":\"Normal\",
            \"C__RECORD_STATUS__ARCHIVED\":\"Archived\",
            \"C__RECORD_STATUS__DELETED\":\"Deleted\",
            \"C__RECORD_STATUS__PURGE\":\"LC__CMDB__RECORD_STATUS__PURGE\"
        },
        \"relationTypes\":{
            \"C__RELATION_TYPE__SOFTWARE\":\"Software assignment\",
            \"C__RELATION_TYPE__CLUSTER_SERVICE\":\"Cluster service assignment\",
            \"C__RELATION_TYPE__BACKUP\":\"Backup\",
            \"C__RELATION_TYPE__ADMIN\":\"Contact assignment\",
            \"C__RELATION_TYPE__USER\":\"Contact assignment\",
            \"C__RELATION_TYPE__CLUSTER_MEMBERSHIPS\":\"Cluster memberships\",
            \"C__RELATION_TYPE__POWER_CONSUMER\":\"Power consumer\",
            \"C__RELATION_TYPE__NETWORK_PORT\":\"Ports\",
            \"C__RELATION_TYPE__VIRTUAL_MACHINE\":\"Virtual machine\",
            \"C__RELATION_TYPE__LOCATION\":\"Location\",
            \"C__RELATION_TYPE__UNIVERSAL_INTERFACE\":\"Interface\",
            \"C__RELATION_TYPE__IP_ADDRESS\":\"Host address\",
            \"C__RELATION_TYPE__CONTROLLER_FC_PORT\":\"FC port\",
            \"C__RELATION_TYPE__CONNECTORS\":\"Connectors\",
            \"C__RELATION_TYPE__LDEV_CLIENT\":\"Logical devices (Client)\",
            \"C__RELATION_TYPE__GROUP_MEMBERSHIPS\":\"Group memberships\",
            \"C__RELATION_TYPE__PERSON_ASSIGNED_GROUPS\":\"Person group memberships\",
            \"C__RELATION_TYPE__DEFAULT\":\"Dependency\",
            \"C__RELATION_TYPE__DATABASE_ACCESS\":\"Database access\",
            \"C__RELATION_TYPE__DATABASE_LINK\":\"Database links\",
            \"C__RELATION_TYPE__DATABASE_GATEWAY\":\"Database gateway\",
            \"C__RELATION_TYPE__DATABASE_INSTANCE\":\"Database instance\",
            \"C__RELATION_TYPE__IT_SERVICE_COMPONENT\":\"Service component\",
            \"C__RELATION_TYPE__REPLICATION_PARTNER\":\"Replication partner\",
            \"C__RELATION_TYPE__SOA_COMPONENTS\":\"SOA-Component\",
            \"C__RELATION_TYPE__SOA_STACKS\":\"SOA-Stacks\",
            \"C__RELATION_TYPE__DBMS\":\"DBMS\",
            \"C__RELATION_TYPE__MOBILE_PHONE\":\"Assigned cards\",
            \"C__RELATION_TYPE__ORGANIZATION\":\"Organization\",
            \"C__RELATION_TYPE__LOGICAL_UNIT\":\"Logical location\",
            \"C__RELATION_TYPE__CONTRACT\":\"Contract assignment\",
            \"C__RELATION_TYPE__CHASSIS\":\"Chassis\",
            \"C__RELATION_TYPE__STACKING\":\"Stacking\",
            \"C__RELATION_TYPE__SHARE_ACCESS\":\"Share Access\",
            \"C__RELATION_TYPE__NET_CONNECTIONS\":\"Network connections\",
            \"C__RELATION_TYPE__CLUSTER_ADM_SERVICE\":\"Administration service\",
            \"C__RELATION_TYPE__OPERATION_SYSTEM\":\"Operating system\",
            \"C__RELATION_TYPE__LAYER2_TRANSPORT\":\"Layer 2 Transport\",
            \"C__RELATION_TYPE__RM_CONTROLLER\":\"Remote Management Controller\",
            \"C__RELATION_TYPE__FILE\":\"Files\",
            \"C__RELATION_TYPE__ORGANIZATION_HEADQUARTER\":\"Headquarter (Organization)\",
            \"C__RELATION_TYPE__VHOST_ADMIN_SERVICE\":\"Virtual host\",
            \"C__RELATION_TYPE__VRRP\":\"VRRP\",
            \"C__RELATION_TYPE__MANUAL\":\"Manual assignment\",
            \"C__RELATION_TYPE__EMERGENCY_PLAN\":\"Emergency plan\",
            \"C__RELATION_TYPE__WAN_CONNECTION\":\"WAN Connection\"
        },
        \"staticObjects\":{
            \"C__OBJ__ROOT_LOCATION\":\"Root location\",
            \"C__OBJ__PERSON_GUEST\":\"guest \",
            \"C__OBJ__PERSON_READER\":\"reader \",
            \"C__OBJ__PERSON_EDITOR\":\"editor \",
            \"C__OBJ__PERSON_AUTHOR\":\"author \",
            \"C__OBJ__PERSON_ARCHIVAR\":\"archivar \",
            \"C__OBJ__PERSON_ADMIN\":\"admin \",
            \"C__OBJ__PERSON_GROUP_READER\":\"Reader\",
            \"C__OBJ__PERSON_GROUP_EDITOR\":\"Editor\",
            \"C__OBJ__PERSON_GROUP_AUTHOR\":\"Author\",
            \"C__OBJ__PERSON_GROUP_ARCHIVAR\":\"Archivar\",
            \"C__OBJ__PERSON_GROUP_ADMIN\":\"Admin\",
            \"C__OBJ__NET_GLOBAL_IPV4\":\"Global v4\",
            \"C__OBJ__NET_GLOBAL_IPV6\":\"Global v6\",
            \"C__OBJ__PERSON_API_SYSTEM\":\"Api System\",
            \"C__OBJ__RACK_SEGMENT__4SLOT\":\"4-Slot\",
            \"C__OBJ__RACK_SEGMENT__8SLOT\":\"8-Slot\",
            \"C__OBJ__RACK_SEGMENT__2SLOT\":\"2-Slot\"
        }
    }
}""")

cmdb_object_type_groups = """
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "id": "1",
            "title": "Software",
            "const": "C__OBJTYPE_GROUP__SOFTWARE",
            "status": "2"
        },
        {
            "id": "2",
            "title": "Infrastructure",
            "const": "C__OBJTYPE_GROUP__INFRASTRUCTURE",
            "status": "2"
        },
        {
            "id": "3",
            "title": "Other",
            "const": "C__OBJTYPE_GROUP__OTHER",
            "status": "2"
        },
        {
            "id": "4",
            "title": "Orhpaned object types",
            "const": "C__OBJTYPE_GROUP__ORPHANED",
            "status": "2"
        },
        {
            "id": "1000",
            "title": "Contact",
            "const": "C__OBJTYPE_GROUP__CONTACT",
            "status": "2"
        }
    ]
}"""

cmdb_object_types_read = """
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": [
        {
            "id": "1",
            "title": "System service",
            "container": "0",
            "const": "C__OBJTYPE__SERVICE",
            "color": "987384",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/service.jpg",
            "icon": "images/icons/silk/application_osx_terminal.png",
            "cats": "4",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "2",
            "title": "Application",
            "container": "0",
            "const": "C__OBJTYPE__APPLICATION",
            "color": "E4B9D7",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/application_xp.png",
            "cats": "20",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "33",
            "title": "Licenses",
            "container": "0",
            "const": "C__OBJTYPE__LICENCE",
            "color": "EADEAC",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/licence.png",
            "icon": "images/icons/silk/key.png",
            "cats": "24",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "35",
            "title": "Operating System",
            "container": "0",
            "const": "C__OBJTYPE__OPERATING_SYSTEM",
            "color": "838683",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/application_osx.png",
            "cats": "98",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "56",
            "title": "Cluster services",
            "container": "0",
            "const": "C__OBJTYPE__CLUSTER_SERVICE",
            "color": "B6BFC9",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/application_cascade.png",
            "cats": "58",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "61",
            "title": "DBMS",
            "container": "0",
            "const": "C__OBJTYPE__DBMS",
            "color": "AAAAAA",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/san.png",
            "icon": "images/icons/silk/database.png",
            "cats": "62",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "62",
            "title": "Database schema",
            "container": "0",
            "const": "C__OBJTYPE__DATABASE_SCHEMA",
            "color": "B0C4DE",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/database_table.png",
            "cats": "60",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "65",
            "title": "Database instance",
            "container": "0",
            "const": "C__OBJTYPE__DATABASE_INSTANCE",
            "color": "61C384",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/service.jpg",
            "icon": "images/icons/silk/database_connect.png",
            "cats": "63",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "66",
            "title": "Middleware",
            "container": "0",
            "const": "C__OBJTYPE__MIDDLEWARE",
            "color": "EEFFDE",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "middleware.png",
            "cats": "75",
            "tree_group": "1",
            "status": "2",
            "type_group": "1",
            "type_group_title": "Software"
        },
        {
            "id": "3",
            "title": "Building",
            "container": "1",
            "const": "C__OBJTYPE__BUILDING",
            "color": "D1695E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/building.png",
            "icon": "images/icons/silk/building.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "4",
            "title": "Rack",
            "container": "1",
            "const": "C__OBJTYPE__ENCLOSURE",
            "color": "D3E3FA",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/enclosure.png",
            "icon": "images/icons/silk/timeline_marker_rotated.png",
            "cats": "1",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "5",
            "title": "Server",
            "container": "0",
            "const": "C__OBJTYPE__SERVER",
            "color": "A2BCFA",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/server.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "6",
            "title": "Switch",
            "container": "0",
            "const": "C__OBJTYPE__SWITCH",
            "color": "B8BED1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/switch.png",
            "icon": "images/icons/silk/drive_network.png",
            "cats": "5",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "7",
            "title": "Router",
            "container": "0",
            "const": "C__OBJTYPE__ROUTER",
            "color": "97D414",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/router.png",
            "icon": "images/icons/silk/drive_web.png",
            "cats": "17",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "8",
            "title": "FC switch",
            "container": "0",
            "const": "C__OBJTYPE__FC_SWITCH",
            "color": "9FC380",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/fcswitch.png",
            "icon": "images/icons/silk/drive_network.png",
            "cats": "16",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "9",
            "title": "Storage system",
            "container": "0",
            "const": "C__OBJTYPE__SAN",
            "color": "F0F0E3",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/san.png",
            "icon": "images/icons/silk/drive_cd_empty.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "10",
            "title": "Client",
            "container": "0",
            "const": "C__OBJTYPE__CLIENT",
            "color": "B9E1BE",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/client.png",
            "icon": "images/icons/silk/computer.png",
            "cats": "15",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "11",
            "title": "Printer",
            "container": "0",
            "const": "C__OBJTYPE__PRINTER",
            "color": "4E93BE",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/printer.png",
            "icon": "images/icons/silk/printer.png",
            "cats": "18",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "12",
            "title": "Air Condition System",
            "container": "0",
            "const": "C__OBJTYPE__AIR_CONDITION_SYSTEM",
            "color": "A88AA7",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/aircond.png",
            "icon": "klima.gif",
            "cats": "9",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "19",
            "title": "KVM switch",
            "container": "0",
            "const": "C__OBJTYPE__KVM_SWITCH",
            "color": "7EDF8D",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/router.png",
            "icon": "images/icons/silk/image_link.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "22",
            "title": "Monitor",
            "container": "0",
            "const": "C__OBJTYPE__MONITOR",
            "color": "DCE0D7",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/monitor.png",
            "icon": "images/icons/silk/monitor.png",
            "cats": "14",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "23",
            "title": "Appliance",
            "container": "0",
            "const": "C__OBJTYPE__APPLIANCE",
            "color": "6EAEBF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/appliances.png",
            "icon": "images/icons/silk/drive_disk.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "24",
            "title": "Telephone system",
            "container": "0",
            "const": "C__OBJTYPE__TELEPHONE_SYSTEM",
            "color": "DDEFFC",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/phonesys.png",
            "icon": "images/icons/silk/telephone_link.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "25",
            "title": "Printbox",
            "container": "0",
            "const": "C__OBJTYPE__PRINTBOX",
            "color": "90AD8B",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/printerbox.png",
            "icon": "images/icons/silk/printer_empty.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "26",
            "title": "Room",
            "container": "1",
            "const": "C__OBJTYPE__ROOM",
            "color": "E4FF9E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/room.png",
            "icon": "room.gif",
            "cats": "3",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "27",
            "title": "Wireless Access Point",
            "container": "0",
            "const": "C__OBJTYPE__ACCESS_POINT",
            "color": "C5C8B4",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/wlan.jpg",
            "icon": "images/icons/silk/television.png",
            "cats": "13",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "38",
            "title": "Phone",
            "container": "0",
            "const": "C__OBJTYPE__PHONE",
            "color": "6886B4",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/phone.png",
            "icon": "images/icons/silk/telephone.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "39",
            "title": "Host",
            "container": "0",
            "const": "C__OBJTYPE__HOST",
            "color": "DADA5E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/server.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "40",
            "title": "Cable",
            "container": "0",
            "const": "C__OBJTYPE__CABLE",
            "color": "B39E92",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/fcswitch.png",
            "icon": "kabel.gif",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "41",
            "title": "Converter",
            "container": "0",
            "const": "C__OBJTYPE__CONVERTER",
            "color": "CAB97D",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/fcswitch.png",
            "icon": "images/icons/silk/connect.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "42",
            "title": "Wiring System",
            "container": "0",
            "const": "C__OBJTYPE__WIRING_SYSTEM",
            "color": "D1695E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/fcswitch.png",
            "icon": "images/icons/silk/text_letter_omega.png",
            "cats": "40",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "43",
            "title": "Patch Panel",
            "container": "0",
            "const": "C__OBJTYPE__PATCH_PANEL",
            "color": "BCDCB9",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/switch.png",
            "icon": "images/icons/silk/drive_rename_dotted.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "44",
            "title": "Amplifier",
            "container": "0",
            "const": "C__OBJTYPE__AMPLIFIER",
            "color": "AF7FF1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/appliances.png",
            "icon": "verstaerker.gif",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "46",
            "title": "Electric power company",
            "container": "0",
            "const": "C__OBJTYPE__ESC",
            "color": "EB8348",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/power.jpg",
            "icon": "images/icons/silk/lightbulb.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "47",
            "title": "Emergency power supply",
            "container": "0",
            "const": "C__OBJTYPE__EPS",
            "color": "E1E79E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/power.jpg",
            "icon": "nea.gif",
            "cats": "43",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "48",
            "title": "Distribution box",
            "container": "0",
            "const": "C__OBJTYPE__DISTRIBUTION_BOX",
            "color": "A5EEA0",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/power.jpg",
            "icon": "verteiler.gif",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "49",
            "title": "Power distribution unit",
            "container": "0",
            "const": "C__OBJTYPE__PDU",
            "color": "43CBE1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/power.jpg",
            "icon": "pdu.gif",
            "cats": "64",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "50",
            "title": "Uninterruptible power supply",
            "container": "0",
            "const": "C__OBJTYPE__UPS",
            "color": "FDD84E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/power.jpg",
            "icon": "images/icons/silk/lightning.png",
            "cats": "42",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "57",
            "title": "Virtual client",
            "container": "0",
            "const": "C__OBJTYPE__VIRTUAL_CLIENT",
            "color": "9FAA7C",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/client.png",
            "icon": "images/icons/silk/computer_link.png",
            "cats": "15",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "58",
            "title": "Virtual host",
            "container": "0",
            "const": "C__OBJTYPE__VIRTUAL_HOST",
            "color": "E6E9DC",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/server_database.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "59",
            "title": "Virtual server",
            "container": "0",
            "const": "C__OBJTYPE__VIRTUAL_SERVER",
            "color": "6D7F92",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/server_chart.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "64",
            "title": "Replication object",
            "container": "0",
            "const": "C__OBJTYPE__REPLICATION",
            "color": "C9BAEF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/silk/arrow_branch.png",
            "cats": "71",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "71",
            "title": "Workplace",
            "container": "0",
            "const": "C__OBJTYPE__WORKSTATION",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/client.png",
            "icon": "images/icons/silk/drive_user.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "73",
            "title": "Switch chassis",
            "container": "1",
            "const": "C__OBJTYPE__SWITCH_CHASSIS",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/enclosure.png",
            "icon": "images/icons/silk/timeline_marker.png",
            "cats": "84",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "74",
            "title": "Blade chassis",
            "container": "1",
            "const": "C__OBJTYPE__BLADE_CHASSIS",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/enclosure.png",
            "icon": "images/icons/silk/timeline_marker.png",
            "cats": "84",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "75",
            "title": "Blade server",
            "container": "0",
            "const": "C__OBJTYPE__BLADE_SERVER",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/drive.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "76",
            "title": "VoIP telephone",
            "container": "0",
            "const": "C__OBJTYPE__VOIP_PHONE",
            "color": "FF8800",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/phone.png",
            "icon": "images/icons/silk/phone_sound.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "84",
            "title": "Country",
            "container": "1",
            "const": "C__OBJTYPE__COUNTRY",
            "color": "ACE177",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/silk/map.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "85",
            "title": "City",
            "container": "1",
            "const": "C__OBJTYPE__CITY",
            "color": "DFB0E1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/city.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "88",
            "title": "Remote Management Controller",
            "container": "0",
            "const": "C__OBJTYPE__RM_CONTROLLER",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/",
            "icon": "images/icons/silk/bullet_picture.png",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "92",
            "title": "Rack segment",
            "container": "1",
            "const": "C__OBJTYPE__RACK_SEGMENT",
            "color": "FFE3A1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/enclosure.png",
            "icon": "images/icons/silk/timeline_marker.png",
            "cats": "84",
            "tree_group": "2",
            "status": "2",
            "type_group": "2",
            "type_group_title": "Infrastructure"
        },
        {
            "id": "13",
            "title": "WAN",
            "container": "0",
            "const": "C__OBJTYPE__WAN",
            "color": "BAE1D2",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/router.png",
            "icon": "images/icons/silk/weather_clouds.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "14",
            "title": "Emergency plan",
            "container": "0",
            "const": "C__OBJTYPE__EMERGENCY_PLAN",
            "color": "C4FFF9",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/emergency.jpg",
            "icon": "images/icons/silk/text_horizontalrule.png",
            "cats": "8",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "28",
            "title": "Contract",
            "container": "0",
            "const": "C__OBJTYPE__MAINTENANCE",
            "color": "7AD3C6",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/maintenance.jpg",
            "icon": "images/icons/silk/text_signature.png",
            "cats": "81",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "29",
            "title": "File",
            "container": "0",
            "const": "C__OBJTYPE__FILE",
            "color": "CDFCF6",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/disk.png",
            "cats": "19",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "31",
            "title": "Layer 3-Net",
            "container": "0",
            "const": "C__OBJTYPE__LAYER3_NET",
            "color": "7EE0EB",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/wlan.jpg",
            "icon": "images/icons/silk/world_link.png",
            "cats": "22",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "32",
            "title": "Cellular Phone",
            "container": "0",
            "const": "C__OBJTYPE__CELL_PHONE_CONTRACT",
            "color": "F2F3BA",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/appliances.png",
            "icon": "images/icons/silk/phone.png",
            "cats": "23",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "36",
            "title": "Object group",
            "container": "0",
            "const": "C__OBJECT_TYPE__GROUP",
            "color": "E1B9DC",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/printerbox.png",
            "icon": "images/icons/silk/sitemap_color.png",
            "cats": "25",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "45",
            "title": "Service",
            "container": "0",
            "const": "C__OBJTYPE__IT_SERVICE",
            "color": "C7F464",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/service.jpg",
            "icon": "images/icons/silk/chart_pie.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "51",
            "title": "SAN Zoning",
            "container": "0",
            "const": "C__OBJTYPE__SAN_ZONING",
            "color": "DDE143",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/san.png",
            "icon": "images/icons/silk/layers.png",
            "cats": "44",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "55",
            "title": "Cluster",
            "container": "0",
            "const": "C__OBJTYPE__CLUSTER",
            "color": "9FAAB7",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/application_cascade.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "68",
            "title": "Crypto card",
            "container": "0",
            "const": "C__OBJTYPE__KRYPTO_CARD",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/page_white_key.png",
            "cats": "76",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "69",
            "title": "SIM card",
            "container": "0",
            "const": "C__OBJTYPE__SIM_CARD",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/application.jpg",
            "icon": "images/icons/silk/page_white_database.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "70",
            "title": "Layer 2 Net",
            "container": "0",
            "const": "C__OBJTYPE__LAYER2_NET",
            "color": "7EE0EB",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/fcswitch.png",
            "icon": "images/icons/silk/page_white_gear.png",
            "cats": "79",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "77",
            "title": "Supernet",
            "container": "1",
            "const": "C__OBJTYPE__SUPERNET",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/wlan.jpg",
            "icon": "images/icons/silk/world.png",
            "cats": "22",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "81",
            "title": "Vehicle",
            "container": "0",
            "const": "C__OBJTYPE__VEHICLE",
            "color": "83C5E1",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/silk/car.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "82",
            "title": "Aircraft",
            "container": "0",
            "const": "C__OBJTYPE__AIRCRAFT",
            "color": "479FC4",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/airplane.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "83",
            "title": "VRRP/HSRP Cluster",
            "container": "0",
            "const": "C__OBJTYPE__CLUSTER_VRRP_HSRP",
            "color": "9FAAB7",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/server.png",
            "icon": "images/icons/silk/application_cascade.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "89",
            "title": "VRRP",
            "container": "0",
            "const": "C__OBJTYPE__VRRP",
            "color": "ABCDEF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/switch.png",
            "icon": "images/icons/silk/disconnect.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "90",
            "title": "Stacking",
            "container": "0",
            "const": "C__OBJTYPE__STACKING",
            "color": "FEDCBA",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/switch.png",
            "icon": "images/icons/silk/drive_stack.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "91",
            "title": "Net zone",
            "container": "0",
            "const": "C__OBJTYPE__NET_ZONE",
            "color": "59BDFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/wlan.jpg",
            "icon": "images/icons/silk/page_white_gear.png",
            "tree_group": "3",
            "status": "2",
            "type_group": "3",
            "type_group_title": "Other"
        },
        {
            "id": "86",
            "title": "Cable tray",
            "container": "1",
            "const": "C__CMDB__OBJTYPE__CABLE_TRAY",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/silk/control_equalizer_blue.png",
            "tree_group": "4",
            "status": "2",
            "type_group": "4",
            "type_group_title": "Orhpaned object types"
        },
        {
            "id": "87",
            "title": "Conduit",
            "container": "1",
            "const": "C__CMDB__OBJTYPE__CONDUIT",
            "color": "FFFFFF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/icons/silk/control_equalizer_blue.png",
            "tree_group": "4",
            "status": "2",
            "type_group": "4",
            "type_group_title": "Orhpaned object types"
        },
        {
            "id": "52",
            "title": "Organization",
            "container": "0",
            "const": "C__OBJTYPE__ORGANIZATION",
            "color": "82E27E",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/building.png",
            "icon": "images/icons/silk/sitemap.png",
            "cats": "45",
            "tree_group": "1000",
            "status": "2",
            "type_group": "1000",
            "type_group_title": "Contact"
        },
        {
            "id": "53",
            "title": "Persons",
            "container": "0",
            "const": "C__OBJTYPE__PERSON",
            "color": "EFAA43",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/tree/person_intern.gif",
            "cats": "48",
            "tree_group": "1000",
            "status": "2",
            "type_group": "1000",
            "type_group_title": "Contact"
        },
        {
            "id": "54",
            "title": "Person groups",
            "container": "0",
            "const": "C__OBJTYPE__PERSON_GROUP",
            "color": "F3FFEF",
            "image": "http://192.168.1.72/i-doit/images/objecttypes/empty.png",
            "icon": "images/tree/group.gif",
            "cats": "52",
            "tree_group": "1000",
            "status": "2",
            "type_group": "1000",
            "type_group_title": "Contact"
        }
    ]
}
"""


def mapping_setup(request):
    # return HttpResponse("Mapping.")
    return render(request, 'mapping/mapping_setup.html', {})


def cmdb_setup(request):
    if "connection" in request.POST:
        connection = request.POST['connection']
    else:
        return render(request, 'mapping/mapping_setup.html', {"error_message": "Please select one option."})
    if "cmdbtype" in request.POST:
        cmdbtype = request.POST['cmdbtype']
    else:
        return render(request, 'mapping/mapping_setup.html', {"error_message": "Please select one option."})
    if cmdbtype == "i-doit":
        if connection == "api":
            return render(request, 'mapping/idoit_api_form.html')
    # TODO: handle database option


def handle_api_idoit(url, username, password, apikey):
    api_url = "http://" + url + "/i-doit/src/jsonrpc.php"
    headers = {}
    headers["Content-Type"] = "application/json"
    headers["X-RPC-Auth-Username"] = username
    headers["X-RPC-Auth-Password"] = password





def process_cmdb_setup(request):
    if request.POST["cmdbtype"] == "i-doit":
        handle_api_idoit(str(request.POST["url"]), str(request.POST["username"]),
                         str(request.POST["password"]), str(request.POST["apikey"]))

        # TODO: handle ci types

    return render(request, 'mapping/idoit_api_form.html')
    # return render(request, 'mapping/cmdb_setup.html', {})
