# Generated by Django 3.0.5 on 2020-06-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.TextField(blank=True, null=True)),
                ('reset_capability', models.TextField(blank=True, null=True)),
                ('creation_class_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('primary_owner_name', models.TextField(blank=True, null=True)),
                ('primary_owner_contact', models.TextField(blank=True, null=True)),
                ('allocation_state', models.TextField(blank=True, null=True)),
                ('enabled_state', models.TextField(blank=True, null=True)),
                ('other_enabled_state', models.TextField(blank=True, null=True)),
                ('requested_state', models.TextField(blank=True, null=True)),
                ('enabled_default', models.TextField(blank=True, null=True)),
                ('time_of_last_state_change', models.TextField(blank=True, null=True)),
                ('transitioning_to_state', models.TextField(blank=True, null=True)),
                ('install_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('health_state', models.TextField(blank=True, null=True)),
                ('communication_status', models.TextField(blank=True, null=True)),
                ('detailed_status', models.TextField(blank=True, null=True)),
                ('operating_status', models.TextField(blank=True, null=True)),
                ('primary_status', models.TextField(blank=True, null=True)),
                ('instance_id', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('element_name', models.TextField(blank=True, null=True)),
                ('generation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'computer_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_creation_class_name', models.TextField(blank=True, null=True)),
                ('cs_name', models.TextField(blank=True, null=True)),
                ('creation_class_name', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('os_type', models.TextField(blank=True, null=True)),
                ('other_type_description', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('last_boot_up_time', models.TextField(blank=True, null=True)),
                ('local_date_time', models.TextField(blank=True, null=True)),
                ('current_time_zone', models.TextField(blank=True, null=True)),
                ('number_of_licensed_users', models.TextField(blank=True, null=True)),
                ('number_of_users', models.TextField(blank=True, null=True)),
                ('number_of_processes', models.TextField(blank=True, null=True)),
                ('max_number_of_processes', models.TextField(blank=True, null=True)),
                ('total_swap_space_size', models.TextField(blank=True, null=True)),
                ('total_virtual_memory_size', models.TextField(blank=True, null=True)),
                ('free_virtual_memory', models.TextField(blank=True, null=True)),
                ('free_physical_memory', models.TextField(blank=True, null=True)),
                ('total_visible_memory_size', models.TextField(blank=True, null=True)),
                ('size_stored_in_paging_files', models.TextField(blank=True, null=True)),
                ('free_space_in_paging_files', models.TextField(blank=True, null=True)),
                ('max_process_memory_size', models.TextField(blank=True, null=True)),
                ('distributed', models.TextField(blank=True, null=True)),
                ('max_processes_per_user', models.TextField(blank=True, null=True)),
                ('enabled_state', models.TextField(blank=True, null=True)),
                ('other_enabled_state', models.TextField(blank=True, null=True)),
                ('requested_state', models.TextField(blank=True, null=True)),
                ('enabled_default', models.TextField(blank=True, null=True)),
                ('time_of_last_state_change', models.TextField(blank=True, null=True)),
                ('transitioning_to_state', models.TextField(blank=True, null=True)),
                ('install_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('health_state', models.TextField(blank=True, null=True)),
                ('communication_status', models.TextField(blank=True, null=True)),
                ('detailed_status', models.TextField(blank=True, null=True)),
                ('operating_status', models.TextField(blank=True, null=True)),
                ('primary_status', models.TextField(blank=True, null=True)),
                ('instance_id', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('element_name', models.TextField(blank=True, null=True)),
                ('generation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operating_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstalledOs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_os', models.TextField(blank=True, null=True)),
                ('computer_system_id7', models.ForeignKey(blank=True, db_column='computer_system_id7', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.ComputerSystem')),
                ('operating_system_id8', models.ForeignKey(blank=True, db_column='operating_system_id8', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.OperatingSystem')),
            ],
            options={
                'db_table': 'installed_os',
                'managed': True,
            },
        ),
    ]
