# Generated by Django 3.0.5 on 2020-06-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(blank=True, null=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('cpe', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('product', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'port',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='installedos',
            name='computer_system_id7',
        ),
        migrations.RemoveField(
            model_name='installedos',
            name='operating_system_id8',
        ),
        migrations.AddField(
            model_name='installedos',
            name='computer_system_id',
            field=models.ForeignKey(blank=True, db_column='computer_system_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.ComputerSystem'),
        ),
        migrations.AddField(
            model_name='installedos',
            name='operating_system_id',
            field=models.ForeignKey(blank=True, db_column='operating_system_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.OperatingSystem'),
        ),
        migrations.CreateModel(
            name='RunningOs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_system_id', models.ForeignKey(blank=True, db_column='computer_system_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.ComputerSystem')),
                ('operating_system_id', models.ForeignKey(blank=True, db_column='operating_system_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.OperatingSystem')),
            ],
            options={
                'db_table': 'running_os',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HasPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_system_id', models.ForeignKey(blank=True, db_column='computer_system_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.ComputerSystem')),
                ('port_id', models.ForeignKey(blank=True, db_column='port_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discovery.Port')),
            ],
            options={
                'db_table': 'has_port',
                'managed': True,
            },
        ),
    ]
