# Generated by Django 3.0.5 on 2020-06-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_auto_20200626_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSystemElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_date', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('health_state', models.TextField(blank=True, null=True)),
                ('communication_status', models.TextField(blank=True, null=True)),
                ('detailed_status', models.TextField(blank=True, null=True)),
                ('operating_status', models.TextField(blank=True, null=True)),
                ('primary_status', models.TextField(blank=True, null=True)),
                ('instance_id', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('element_name', models.TextField(blank=True, null=True)),
                ('generation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'managed_system_element',
                'managed': True,
            },
        ),
    ]
