# Generated by Django 3.0.5 on 2020-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_managedsystemelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasport',
            name='computer_system_id',
        ),
        migrations.RemoveField(
            model_name='hasport',
            name='port_id',
        ),
        migrations.RemoveField(
            model_name='installedos',
            name='computer_system_id',
        ),
        migrations.RemoveField(
            model_name='installedos',
            name='operating_system_id',
        ),
        migrations.DeleteModel(
            name='ManagedSystemElement',
        ),
        migrations.RemoveField(
            model_name='runningos',
            name='computer_system_id',
        ),
        migrations.RemoveField(
            model_name='runningos',
            name='operating_system_id',
        ),
        migrations.DeleteModel(
            name='ComputerSystem',
        ),
        migrations.DeleteModel(
            name='HasPort',
        ),
        migrations.DeleteModel(
            name='InstalledOs',
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
        migrations.DeleteModel(
            name='RunningOs',
        ),
    ]
